# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    reviewers:
      - "lindsaygelle"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "09:00"
      timezone: "Australia/Sydney"

  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "lindsaygelle"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "09:00"
      timezone: "Australia/Sydney"

  - package-ecosystem: "pip"
    directory: "/"
    reviewers:
      - "lindsaygelle"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Australia/Sydney"
